kind: Service
apiVersion: v1
metadata:
  name: leave-management-fe-service
 # annotations:
 #   service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  selector:
    app: leave-management-fe
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
  - name: https
    port: 443
    targetPort: 443
  type: LoadBalancer
  #loadBalancerIP: 192.168.5.86
